In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np

In [4]:
with open("vishal_new.html","r",encoding="utf-8") as f :
    res = f.read()
soup = BeautifulSoup(res,"html.parser")

In [53]:
d={'mobilename':[],'star':[],'rating':[],'review':[],'display':[],'camera':[],'new_price':[],'old_price':[],'discount':[]}
box=soup.find_all("div",class_="_3pLy-c row")
for i in box:
    d['mobilename'].append(i.find('div',class_="_4rR01T").text.strip())
    d['star'].append(float(i.find('div',class_="_3LWZlK").text.strip()))
    # print("rating",i.find('span',class_="_2_R_DZ").text.strip().split("\xa0&\xa0")[0][:-8])
    # print("review",i.find('span',class_="_2_R_DZ").text.strip().split("\xa0&\xa0")[1][:-8])
    d['rating'].append(int(i.find('span',class_="_2_R_DZ").text.strip().split("\xa0&\xa0")[0][:-8].replace(",","")))
    d['review'].append(int(i.find('span',class_="_2_R_DZ").text.strip().split("\xa0&\xa0")[1][:-8].replace(",","")))
    d['display'].append(i.find("ul",class_="_1xgFaf").find_all("li")[1].text.strip())
    d['camera'].append(i.find("ul",class_="_1xgFaf").find_all("li")[2].text.strip())
    d['new_price'].append(i.find('div',class_="_30jeq3 _1_WHN1").text.strip()[1:])
    try:
        d['old_price'].append(i.find('div',class_="_3I9_wc _27UcVY").text.strip())
    except:
        d['old_price'].append(np.nan)
    try:
        d['discount'].append(i.find('div',class_="_3Ay6Sb").text.strip())
    except:
        d['discount'].append(np.nan)
df = pd.DataFrame(d)
df

,mobilename,star,rating,review,display,camera,new_price,old_price,discount
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,829,265,13.21 cm (5.2 inch) Full HD Display,12MP + 12MP | 8MP Front Camera,"39,999","₹40,999",2% off
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,829,265,13.21 cm (5.2 inch) Full HD Display,12MP + 12MP | 8MP Front Camera,"39,999","₹40,999",2% off
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,3234,364,16.76 cm (6.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,"49,999","₹1,01,999",50% off
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,4262,285,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,"44,999","₹95,999",53% off
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,559,96,16.94 cm (6.67 inch) Full HD+ Display,200MP + 50MP + 12MP | 60MP Front Camera,"49,999","₹74,999",33% off
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,559,96,16.94 cm (6.67 inch) Full HD+ Display,200MP + 50MP + 12MP | 60MP Front Camera,"49,999","₹74,999",33% off
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,415,39,16.26 cm (6.4 inch) Full HD+ Display,50MP + 12MP + 5MP | 32MP Front Camera,"40,999","₹45,999",10% off
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,246,35,16.64 cm (6.55 inch) Display,48MP + 2MP + 16MP,"46,999","₹47,999",2% off
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,3234,364,16.76 cm (6.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,"49,999","₹1,01,999",50% off
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,246,35,16.64 cm (6.55 inch) Display,48MP + 2MP + 16MP,"47,349","₹47,999",1% off
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,3688,552,16.94 cm (6.67 inch) Full HD+ Display,108MP + 13MP + 5MP | 20MP Front Camera,"38,849","₹47,999",19% off
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,4262,285,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,"44,999","₹95,999",53% off
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,970,142,16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,"49,999","₹57,990",13% off
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,970,142,16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,"47,999","₹57,990",17% off
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,274,26,16.81 cm (6.62 inch) Display,50MP Rear Camera,"48,999",NaN,NaN
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,274,26,16.81 cm (6.62 inch) Display,50MP Rear Camera,"46,999",NaN,NaN
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4.0,286,30,16.64 cm (6.55 inch) Display,48MP Rear Camera,"49,999",NaN,NaN
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,195660,11232,15.49 cm (6.1 inch) Liquid Retina HD Display,12MP + 12MP | 12MP Front Camera,"46,999","₹48,900",3% off
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,369,37,16.64 cm (6.55 inch) Display,48MP Rear Camera,"49,999",NaN,NaN
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,246,35,17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,"43,990","₹79,990",45% off
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,246,35,17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,"43,900","₹79,990",45% off
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,2866,436,17.02 cm (6.7 inch) Quad HD Display,50MP + 50MP + 2MP | 32MP Front Camera,"49,999","₹57,999",13% off
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,3791,691,16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,"48,999","₹54,990",10% off
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,218,28,17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,"48,880","₹84,999",42% off

In [55]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
with open('List of state and union territory capitals in India - Wikipedia (5_28_2025 8：46：50 AM).html','r',encoding = 'utf-8') as f:
    res = f.read()
soup = BeautifulSoup(res,'html.parser')
table = soup.find('table',class_ = 'wikitable sortable jquery-tablesorter')

head = table.find('thead')
col = []
for i in head.find_all('th'):
    col.append(i.text.strip())
col[5] = col[5].split('\n')[0]
col

body = table.find('tbody')
d = {col[0] : [],col[1] : [],col[2] : [],col[3] : [],col[4] : [],col[5] : []}
for i in body.find_all('tr'):
    l = i.find_all('td')
    d[col[0]].append(l[0].text.strip())
    d[col[1]].append(l[1].text.strip())
    d[col[2]].append(l[2].text.strip())
    d[col[3]].append(l[3].text.strip())
    d[col[4]].append(l[4].text.strip())
    d[col[5]].append(l[5].text.strip())


df = pd.DataFrame(d)
df

,State,Administrative/Executive capital,Legislative capital,Judicial capital,Year ofestablishment,Former capital
0,Andhra Pradesh,Amaravati,Amaravati,Amaravati,1956,Hyderabad[a](1956–2014)
1,Arunachal Pradesh,Itanagar,Itanagar,Guwahati,1987,—
2,Assam,Dispur,Dispur,Guwahati,1972,Shillong[b] (1950–1972)
3,Bihar,Patna,Patna,Patna,1950,—
4,Chhattisgarh,Raipur[c],Raipur,Bilaspur,2000,—
5,Goa,Panaji[d],Porvorim,Mumbai,1987,—
6,Gujarat,Gandhinagar,Gandhinagar,Ahmedabad,1960,Ahmedabad (1960–1970)
7,Haryana,Chandigarh,Chandigarh,Chandigarh,1966,—
8,Himachal Pradesh,Shimla,Shimla (Summer)Dharamshala (Winter)[5],Shimla,1971,—
9,Jharkhand,Ranchi,Ranchi,Ranchi,2000,—
10,Karnataka,Bengaluru,Bengaluru (Summer)Belgaum (Winter),Bengaluru,1956,—
11,Kerala,Thiruvananthapuram,Thiruvananthapuram,Kochi[6],1956,—
12,Madhya Pradesh,Bhopal,Bhopal,Jabalpur,1956,—
13,Maharashtra,Mumbai[e],Mumbai (Summer)Nagpur (Winter),Mumbai,1960,—
14,Manipur,Imphal,Imphal,Imphal,1972,—
15,Meghalaya,Shillong,Shillong,Shillong,1972,—
16,Mizoram,Aizawl,Aizawl,Guwahati,1987,—
17,Nagaland,Kohima,Kohima,Guwahati,1963,—
18,Odisha,Bhubaneswar,Bhubaneswar,Cuttack,1950,—
19,Punjab,Chandigarh,Chandigarh,Chandigarh,1966,—
20,Rajasthan,Jaipur,Jaipur,Jodhpur,1950,—
21,Sikkim,Gangtok[f],Gangtok,Gangtok,1975,—
22,Tamil Nadu,Chennai[g],Chennai,Chennai,1956,—
23,Telangana,Hyderabad,Hyderabad,Hyderabad,2014,—
24,Tripura,Agartala,Agartala,Agartala,1972,—
25,Uttar Pradesh,Lucknow,Lucknow,Prayagraj,1950,—
26,Uttarakhand,Dehradun,Bhararisain (summer)[8]Dehradun (winter),Nainital,2000,—
27,West Bengal,Kolkata,Kolkata,Kolkata,1950,—